#!/bin/bash
# YOU ARE DEAD. by rupa. WTFPL

YOU=x
LEVEL=1
MAX_LEVEL=10
SCORE=0

for x; do case $x in
    -[0-9]) MAX_LEVEL=${x:1};;
    -e) unset MAX_LEVEL;;
    -h) echo "KEYS: WASD. YOU ARE DEAD."; exit;;
esac; shift; done

trap 'tput cnorm -- normal' EXIT
tput civis -- invisible

CHOICES="~.      "

you_win() {
    printf "$DUNGEON\nLEVEL $LEVEL, SCORE $SCORE. YOU WIN. YOU ARE DEAD.\n"
    exit
}

game_over() {
    printf "\nLEVEL $LEVEL, SCORE $SCORE. YOU ARE DEAD.\n"
    exit 1
}

build_dungeon() {
    DUNGEON=" "
    local COUNTER=2
    while [ $COUNTER -le $(tput cols) ]; do
        DUNGEON="$DUNGEON${CHOICES:$((RANDOM % ${#CHOICES})):1}"
        COUNTER=$((COUNTER + 1));
    done
}

build_dungeon

while :; do

    COLS=$(tput cols)
    F=0
    OLDYOU=$YOU

    printf "$DUNGEON\r%*s$YOU\r" $((SCORE % $COLS))

    read -s -n 1

    case "$REPLY" in
        w) YOU='~';;
        a) YOU=x
           [ $((SCORE % $COLS)) = 0 ] && game_over
           SCORE=$((SCORE - 1))
           ;;
        s) YOU=.;;
        d) YOU=x
           SCORE=$((SCORE + 1))
           F=1
           ;;
    esac

    [ $SCORE -lt 0 ] && game_over

    [ "$F" = 1 ] || continue

    THING=${DUNGEON:$((SCORE % $COLS)):1}

    [ "$THING" != "" -a "$THING" != " " -a "$OLDYOU" != "$THING" ] && game_over

    [ $((SCORE % $COLS)) = 0 ] && {
        [ "$MAX_LEVEL" -a "$LEVEL" -ge "$MAX_LEVEL" ] && you_win
        LEVEL=$((LEVEL + 1))
        printf "$DUNGEON\nLEVEL $LEVEL\n"
        build_dungeon
    }

done
